
const db = globalThis.__B44_DB__;

import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "@/lib/AuthContext";
import { ACTIVE_CLASS_CHANGED_EVENT, getActiveStudentAccount } from "@/lib/studentContext";
import { supabase } from '@/api/supabaseClient';

import ClayButton from "@/components/ClayButton";
import ClayCard from "@/components/ClayCard";
import ClayChip from "@/components/ClayChip";
import { Rocket, History, Zap } from "lucide-react";
import MissionAssessment from "@/components/student/MissionAssessment";
import { ROUTES } from '@/lib/routes';
import MascotWidget from "@/components/MascotWidget";
import NovaEmptyState from "@/components/mascot/NovaEmptyState";
import NovaMessage from "@/components/NovaMessage";
import { UIAsset } from "@/components/visual/UIAsset";
import PanelSkeleton from "@/components/PanelSkeleton";
import { completeLearningReview, ensureDailyPowerUp, getPersonalRewardDashboard, powerUpAppliesToClassroom } from '@/lib/secureActions';
import { formatMissionDeadline, isDailyFoundationMission, isMissionLocked, manilaDateKey } from '@/lib/missionProgress';

export default function StudentMissions() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [historyMissionId, setHistoryMissionId] = useState(null);

  useEffect(() => {
    load();
    const refresh = () => load();
    window.addEventListener(ACTIVE_CLASS_CHANGED_EVENT, refresh);
    return () => window.removeEventListener(ACTIVE_CLASS_CHANGED_EVENT, refresh);
  }, [user]);

  async function load() {
    if (!user) return;
    const account = await getActiveStudentAccount(user.id);
    if (!account) { navigate(ROUTES.STUDENT.ONBOARDING); return; }
    const [group, classroom] = await Promise.all([
      db.entities.Group.get(account.group_id),
      db.entities.Classroom.get(account.classroom_id),
    ]);
    const classroomId = group.classroom_id;
    // The Power-Up is a Mathematics activity. A student in another subject has
    // no Power-Up coming, so the whole section stays hidden rather than telling
    // them to wait for a teacher's review that will never happen.
    const powerUpApplies = await powerUpAppliesToClassroom(classroomId).catch(() => false);
    // Materialise today's Daily Math Power-Up before reading the list, so a
    // student who has never opened the app still has one waiting.
    let powerUp = null;
    if (powerUpApplies) {
      try {
        powerUp = await ensureDailyPowerUp(classroomId);
      } catch (err) {
        // A missing Power-Up must never block the teacher's missions from
        // loading, but the reason matters to the teacher who reports it.
        powerUp = null;
        console.warn('[power-up] not generated for today:', err?.message || err);
      }
    }
    const [{ data: dashboard, error: dashboardError }, personalRewards] = await Promise.all([
      supabase.rpc('get_student_mission_dashboard', { p_classroom_id: classroomId }),
      getPersonalRewardDashboard(classroomId),
    ]);
    if (dashboardError) throw dashboardError;
    const missions = [...(dashboard?.missions || [])];
    // A Power-Up generated after the RPC snapshot still belongs in today's list,
    // but only once a teacher has approved it. The engine creates it pending, so
    // an unapproved row must never reach the student's screen.
    if (powerUp && powerUp.approval_status === 'approved' && powerUp.is_active
      && !missions.some((m) => m.id === powerUp.id)) missions.unshift(powerUp);
    // The daily Power-Up is generated by UniClass, not by the teacher, and it
    // is rebuilt every day. It gets its own section instead of competing with
    // teacher-assigned work for attention.
    const powerUps = missions.filter(isDailyFoundationMission);
    const active = missions.filter((m) => !isDailyFoundationMission(m));
    const subs = dashboard?.submissions || [];
    const earned = Number(personalRewards?.earned || 0);
    const spent = Number(personalRewards?.spent || 0);
    const available = Math.max(0, Number(personalRewards?.available || 0));
    const dueReviews = (dashboard?.reviews || []).filter((review) => new Date(review.next_review_at) <= new Date());
    setData({ account, group, classroom, missions, active, powerUps, powerUpApplies, subs, earned, spent, available, dueReviews, classification: { tag: dashboard?.classification || 'At Risk' } });
  }

  async function markReviewed(review, correct) {
    await completeLearningReview(review.id, correct);
    setData((current) => ({ ...current, dueReviews: current.dueReviews.filter((item) => item.id !== review.id) }));
  }

  if (!data) return <PanelSkeleton />;

  const { group, classroom, active, powerUps, powerUpApplies, subs, earned, spent, available, dueReviews, classification } = data;
  const walletBlocked = available >= 30;
  const completedMissions = active.filter((m) => subs.find((s) => s.mission_id === m.id));
  const currentMissions = active.filter((m) => !subs.find((s) => s.mission_id === m.id));
  const gradedCount = completedMissions.length;
  // Today's Power-Up, and only a teacher's approved one. The engine generates
  // it every morning but holds it back until it is reviewed, so until then
  // there is genuinely no Power-Up to do today.
  const todayPowerUp = powerUps.find((m) => m.auto_daily_date === manilaDateKey()) || null;
  const hasPowerUp = Boolean(todayPowerUp);
  const powerUpSubmission = todayPowerUp ? subs.find((s) => s.mission_id === todayPowerUp.id) : null;
  const powerUpLocked = todayPowerUp ? isMissionLocked(todayPowerUp) : false;
  let powerUpQuestions = 5;
  let powerUpParseFailed = false;
  // Not swallowed. A payload that does not parse is exactly the 20261120
  // incident, where every mission rendered with zero questions and nothing said
  // why. Say so on screen instead of quietly showing a wrong count.
  try { powerUpQuestions = JSON.parse(todayPowerUp?.ai_content || '{}').questions?.length || 5; }
  catch { powerUpParseFailed = Boolean(todayPowerUp); }

  return (
    <div className="mx-auto max-w-5xl space-y-5 sm:space-y-6">
      {powerUpParseFailed && (
        <p className="rounded-xl border-2 border-clay-coral/40 bg-clay-coral/10 p-3 text-sm font-bold text-clay-coral">
          Today&apos;s Power-Up could not be read, so it cannot be shown. Please tell your teacher.
        </p>
      )}
      <section className="grid gap-4 lg:grid-cols-[1fr_minmax(290px,.75fr)] lg:items-center">
        <div>
          <p className="text-sm font-semibold text-[var(--uc-purple)]">Your learning quests</p>
          <h1 className="uc-page-title mt-1 text-3xl sm:text-4xl">My missions</h1>
          <p className="mt-1 text-sm leading-relaxed text-ink/60">Complete your own teacher-assigned activities, learn from feedback, and use your XP for learning boosts or profile collectibles.</p>
          <p className="mt-2 text-xs font-semibold text-ink/55">Viewing: {classroom?.grade_level} · {classroom?.section} · {classroom?.subject || 'Class'}</p>
          <p className="mt-2 inline-flex rounded-full bg-[var(--uc-green-soft)] px-3 py-1 text-xs font-semibold text-[var(--uc-navy-950)]">Learning status: {classification.tag}</p>
        </div>
        <NovaMessage variant="assessment" tone="violet" title="Ready for your next step?">Take your time. Feedback will help you strengthen each topic.</NovaMessage>
      </section>

      <ClayCard color="purple" className="p-5">
        <div className="flex items-center gap-4">
          <div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-white/15"><UIAsset name="assessment" className="h-14 w-14" /></div>
          <div className="flex-1 text-white">
            <p className="font-mono font-extrabold text-4xl leading-none">{available}</p>
            <p className="font-display font-bold text-sm">XP available to redeem</p>
            <p className="text-xs text-white/70">{`Earned ${earned} XP - Spent ${spent} XP · 10 XP = 1 participation point`}</p>
          </div>
        </div>
        <Link to={ROUTES.STUDENT.REWARDS} className="mt-4 inline-flex items-center gap-1 text-xs font-display font-bold text-white underline">
          <span>Use 10 XP</span><span>Or choose a personal reward</span>
        </Link>
      </ClayCard>
      {walletBlocked && <ClayCard color="coral" className="p-4"><p className="font-display font-bold">Missions are paused while your XP wallet is full.</p><p className="mt-1 text-sm text-ink/70">Open Rewards and redeem at least 10 XP to bring your available balance below 30 XP, then continue with your missions.</p></ClayCard>}

      {dueReviews?.length > 0 && (
        <ClayCard color="sky" className="p-4">
          <div className="flex items-center justify-between gap-3 mb-3">
            <div><p className="font-display font-bold">Review queue</p><p className="text-xs text-ink/60">Short practice helps the tricky parts stick.</p></div>
            <ClayChip color="sun">{dueReviews.length} due</ClayChip>
          </div>
          <div className="space-y-2">
            {dueReviews.slice(0, 5).map((review) => (
              <div key={review.id} className="rounded-xl border-2 border-ink/15 bg-cream p-3">
                <p className="text-sm font-display font-bold">{review.prompt_text}</p>
                <p className="text-[11px] text-ink/50 mt-1">{review.review_count ? `Reviewed ${review.review_count} time${review.review_count === 1 ? "" : "s"}` : "Needs a first review"}</p>
                <div className="flex gap-2 mt-2"><ClayButton size="sm" color="coral" onClick={() => markReviewed(review, false)}>Still tricky</ClayButton><ClayButton size="sm" color="lime" onClick={() => markReviewed(review, true)}>Got it</ClayButton></div>
              </div>
            ))}
          </div>
        </ClayCard>
      )}

      {active.length > 0 && (
        <ClayCard className="p-4 sm:p-5">
          <div className="flex justify-between mb-2">
            <span className="flex items-center gap-2 font-display font-bold text-sm"><UIAsset name="analytics" className="h-7 w-7" /> Mission progress</span>
            <span className="font-mono text-sm">{gradedCount}/{active.length} graded</span>
          </div>
          <div className="h-5 rounded-full border-2 border-ink bg-cream overflow-hidden">
            <div className="h-full bg-clay-lime" style={{ width: `${active.length ? (gradedCount / active.length) * 100 : 0}%` }} />
          </div>
          <p className="text-xs text-ink/60 mt-2">{gradedCount < active.length ? "Complete the remaining missions to earn more XP!" : "All active missions graded. Nice work!"}</p>
        </ClayCard>
      )}

      {powerUpApplies && (
      <section>
          <h2 className="font-display font-bold text-lg mb-2 flex items-center gap-2"><Zap className="w-5 h-5" /> Daily Math Power-Up</h2>
          <p className="text-xs text-ink/60 mb-2">A short daily practice your classroom unlocks automatically. A new one arrives each morning.</p>
          <div className="space-y-2">
            {hasPowerUp ? (
              <>
                <ClayCard color="sky" className="p-4">
                  <div className="flex items-start justify-between gap-3">
                    <div className="min-w-0">
                      <p className="font-display font-bold">Today's Power-Up</p>
                      <div className="flex flex-wrap gap-2 mt-2">
                        <ClayChip color="sun">{`+${todayPowerUp.xp_reward} XP`}</ClayChip>
                        <ClayChip color="purple">{`${powerUpQuestions} questions`}</ClayChip>
                        {powerUpSubmission
                          ? <ClayChip color="lime">{`${powerUpSubmission.score}/${powerUpQuestions} done`}</ClayChip>
                          : <ClayChip color="sun">{powerUpLocked ? 'Closed' : 'To do'}</ClayChip>}
                      </div>
                    </div>
                    {powerUpSubmission && <MascotWidget state="excited" size="sm" />}
                  </div>
                </ClayCard>
                {powerUpLocked && !powerUpSubmission && <ClayCard className="p-4"><p className="font-display font-bold text-clay-coral">Today's Power-Up has closed.</p><p className="text-xs text-ink/60 mt-1">A fresh one arrives tomorrow morning. Keep practising in your mission history in the meantime.</p></ClayCard>}
                {!powerUpLocked && (walletBlocked && !powerUpSubmission ? <ClayCard className="p-4"><p className="font-display font-bold">Open Rewards and redeem 10 XP to start this mission.</p></ClayCard> : <MissionAssessment mission={todayPowerUp} group={group} userId={user.id} existing={powerUpSubmission} onDone={load} />)}
              </>
            ) : (
              <ClayCard className="p-4">
                <p className="font-display font-bold text-clay-coral">No Power-Up today</p>
                <p className="text-xs text-ink/60 mt-1">Your teacher reviews the daily Power-Up before it opens, so there is nothing to do here yet. Check back after it is approved.</p>
              </ClayCard>
            )}
          </div>
      </section>
      )}

      <div>
        <h2 className="font-display font-bold text-lg mb-2 flex items-center gap-2"><Rocket className="w-5 h-5" /> Active Missions</h2>
        {currentMissions.length === 0 ? (
          <NovaEmptyState
            variant="teacher"
            title="No active missions"
            description={powerUpApplies
              ? "Your teacher-assigned missions will appear here. Today’s Daily Math Power-Up is shown above."
              : "This selected classroom is not a Mathematics class, so it does not receive the Daily Math Power-Up. Use the class switcher in the header to view a Mathematics classroom."}
          />
        ) : (
          <div className="grid gap-3 sm:grid-cols-2">
            {currentMissions.map((m) => {
              const sub = subs.find((s) => s.mission_id === m.id);
              const isAi = m.formative_type && m.formative_type !== "manual";
              let questionMax = m.max_score;
              if (isAi && m.formative_type !== 'drag_drop') {
                try { questionMax = JSON.parse(m.ai_content || '{}').questions?.length || m.max_score; } catch {}
              }
              const header = (
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <p className="font-display font-bold">{m.title}</p>
                    {m.description && <p className="text-xs text-ink/60 mt-0.5">{m.description}</p>}
                    <div className="flex flex-wrap gap-2 mt-2">
                      <ClayChip color="sun">{`+${m.xp_reward} XP`}</ClayChip>
                      <ClayChip color="purple">{`/${questionMax} questions`}</ClayChip>
                      {formatMissionDeadline(m) && <ClayChip color={isMissionLocked(m) ? "coral" : "sky"}>{isMissionLocked(m) ? `Locked ${formatMissionDeadline(m)}` : `Due ${formatMissionDeadline(m)}`}</ClayChip>}
                      {isAi && <ClayChip color="purple">{m.formative_type.replace("_", " ")}</ClayChip>}
                    </div>
                  </div>
                  {sub ? <ClayChip color="lime">{`${sub.score}/${questionMax} -> ${sub.xp_earned} XP`}</ClayChip> : <ClayChip color="sun">To do</ClayChip>}
                </div>
              );
              if (isAi) {
                return (
                  <div key={m.id} className="space-y-2 sm:col-span-2">
                    <ClayCard className="p-4"><div className="mb-3 flex items-center gap-2"><MascotWidget state="quest" size="sm" /><span className="text-xs font-display font-bold">Generated by UniClass AI Assistant</span></div>{m.image_url && <img src={m.image_url} alt={`${m.title} illustration`} className="mb-3 max-h-64 w-full rounded-xl border-2 border-ink object-cover" loading="lazy" />}{header}</ClayCard>
                    {isMissionLocked(m) ? <ClayCard className="p-4"><p className="font-display font-bold text-clay-coral">This mission is locked.</p><p className="text-xs text-ink/60 mt-1">Its deadline was {formatMissionDeadline(m)}. You can still view completed missions in your history.</p></ClayCard> : walletBlocked && !sub ? <ClayCard className="p-4"><p className="font-display font-bold">Open Rewards and redeem 10 XP to start this mission.</p></ClayCard> : <MissionAssessment mission={m} group={group} userId={user.id} existing={sub} onDone={load} />}
                  </div>
                );
              }
              return <ClayCard key={m.id} className="p-4">{header}</ClayCard>;
            })}
          </div>
        )}
      </div>

      {completedMissions.length > 0 && (
        <div>
          <h2 className="font-display font-bold text-lg mb-2 flex items-center gap-2"><History className="w-5 h-5" /> Mission History</h2>
          <p className="text-xs text-ink/60 mb-2">Open a completed mission anytime to review your answers and feedback.</p>
          <div className="space-y-2">
            {completedMissions.map((m) => {
              const sub = subs.find((s) => s.mission_id === m.id);
              const isAi = m.formative_type && m.formative_type !== "manual";
              let questionMax = m.max_score;
              if (isAi && m.formative_type !== 'drag_drop') {
                try { questionMax = JSON.parse(m.ai_content || '{}').questions?.length || m.max_score; } catch {}
              } else if (isAi && m.formative_type === 'drag_drop') {
                try { questionMax = JSON.parse(m.ai_content || '{}').left?.length || m.max_score; } catch {}
              }
              const expanded = historyMissionId === m.id;
              return <div key={m.id} className="space-y-2">
                <ClayCard className="p-3">
                  <div className="flex items-center justify-between gap-3">
                    <div className="min-w-0"><p className="font-display font-bold truncate">{m.title}</p><p className="text-xs text-ink/55">{isAi ? 'AI formative assessment' : 'Teacher-graded mission'}{m.deadline ? ` · Due ${m.deadline}` : ''}</p></div>
                    <div className="flex items-center gap-2 shrink-0"><ClayChip color="lime">{sub.score}/{questionMax}</ClayChip><ClayButton type="button" size="sm" color="sky" onClick={() => setHistoryMissionId(expanded ? null : m.id)}>{expanded ? 'Close' : isAi ? 'Review' : 'View'}</ClayButton></div>
                  </div>
                </ClayCard>
                {expanded && (isAi ? <MissionAssessment mission={m} group={group} userId={user.id} existing={sub} onDone={load} /> : <ClayCard className="p-3"><p className="text-sm font-display font-bold">Completed</p><p className="text-xs text-ink/60 mt-1">This mission is teacher-graded. Ask your teacher for written feedback or a score review.</p></ClayCard>)}
              </div>;
            })}
          </div>
        </div>
      )}
    </div>
  );
}
