import { useNavigate } from "react-router-dom";
import { ArrowRight, Check, ClipboardCheck, QrCode, Sparkles, UsersRound } from "lucide-react";
import { useAuth } from "@/lib/AuthContext";
import { ROUTES } from "@/lib/routes";
import RoleRouter from "@/pages/RoleRouter";
import ThemeToggle from "@/components/ThemeToggle";
import BrandMark from "@/components/BrandMark";
import { NovaAsset, UIAsset } from "@/components/visual/UIAsset";

const coreTools = [
  ["classes", "Set up each class", "Teachers add a grade, section, subject, meeting days, and a class code. Students join the right class, individually or in groups."],
  ["attendance", "Take attendance simply", "Open a QR check-in for class, let students scan or enter its code, and keep an accurate attendance history."],
  ["assessment", "Assess work in context", "Create activities and formative missions, review submissions, record scores, and follow up with evidence when a score needs attention."],
  ["reward", "Make effort visible", "Missions earn personal XP. Groups build shared points, request rewards, collect badges, and follow the class leaderboard."],
];

function Button({ children, className = "", ...props }) {
  return <button className={`clay-btn rounded-2xl px-5 py-3 text-sm font-semibold sm:text-base ${className}`} {...props}>{children}</button>;
}

function WorkflowCard({ icon, label, title, copy, tone = "bg-white/85" }) {
  return <div className={`rounded-2xl ${tone} p-4 shadow-sm ring-1 ring-white/80`}>
    <div className="flex items-start gap-3"><div className="uc-icon-tile h-11 w-11 shrink-0 bg-gradient-to-br from-[#f0eeff] to-[#def0ff]"><UIAsset name={icon} className="h-8 w-8" /></div><div className="min-w-0"><p className="text-[11px] font-semibold uppercase tracking-[.12em] text-clay-purple">{label}</p><h3 className="mt-0.5 text-lg leading-tight">{title}</h3><p className="mt-1 text-sm leading-snug text-ink/70">{copy}</p></div></div>
  </div>;
}

export default function Landing() {
  const { isAuthenticated, isLoadingAuth } = useAuth();
  const navigate = useNavigate();
  if (isLoadingAuth) return <div className="uc-app-background flex min-h-screen items-center justify-center"><div className="h-9 w-9 animate-spin rounded-full border-4 border-clay-purple/25 border-t-clay-purple" /></div>;
  if (isAuthenticated) return <RoleRouter />;

  return <div className="uc-app-background min-h-screen overflow-x-hidden text-ink">
    <header className="sticky top-0 z-30 border-b border-white/65 bg-white/70 px-4 py-3 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4">
      <a href="#top" className="flex items-center gap-2.5" aria-label="UniClass home"><BrandMark /><span className="text-2xl font-semibold tracking-tight">UniClass</span></a>
      <nav className="hidden items-center gap-6 text-sm font-medium text-ink/75 md:flex"><a href="#tools" className="transition hover:text-clay-purple">Tools</a><a href="#for-whom" className="transition hover:text-clay-purple">Who it’s for</a><a href="#how-it-works" className="transition hover:text-clay-purple">How it works</a></nav>
      <div className="flex items-center gap-2"><ThemeToggle /><Button onClick={() => navigate(ROUTES.LOGIN)} className="hidden bg-white/90 sm:inline-flex">Log in</Button><Button onClick={() => navigate(ROUTES.REGISTER)} className="bg-clay-purple text-white">Create account <ArrowRight className="h-4 w-4" /></Button></div>
    </div></header>

    <main id="top" className="relative z-10 mx-auto max-w-[1440px] px-4 sm:px-6 lg:px-8">
      <section className="grid items-center gap-9 py-12 lg:grid-cols-[.94fr_1.06fr] lg:py-20">
        <div className="max-w-2xl"><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/90 bg-white/78 px-3.5 py-2 text-xs font-semibold uppercase tracking-[.12em] text-clay-purple shadow-sm"><Sparkles className="h-4 w-4" /> Class management that students can feel</p><h1 className="text-5xl font-semibold leading-[.98] tracking-tight sm:text-6xl xl:text-[4.5rem]">Run the classroom. <span className="text-clay-purple">Grow the team.</span></h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-ink/80">UniClass is a shared classroom workspace for teachers and students. It brings class setup, QR attendance, activities, formative missions, scores, recognition, and group progress into one clear routine.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button onClick={() => navigate(ROUTES.REGISTER)} className="bg-clay-purple text-white">Set up UniClass <ArrowRight className="h-4 w-4" /></Button><Button onClick={() => navigate(ROUTES.LOGIN)} className="bg-white/90">Log in to your class</Button></div><div className="mt-8 grid max-w-xl grid-cols-2 gap-x-5 gap-y-2 text-sm font-medium text-ink/80 sm:grid-cols-3">{["Class codes", "QR attendance", "Activities & missions", "Scores & evidence", "XP & rewards", "Badges & leaderboard"].map((item) => <span key={item} className="inline-flex items-center gap-1.5"><Check className="h-4 w-4 shrink-0 text-clay-purple" />{item}</span>)}</div></div>

        <section aria-label="UniClass classroom workflow" className="uc-landing-float relative overflow-hidden rounded-[30px] border border-white/85 bg-white/75 p-4 shadow-[0_22px_50px_rgba(47,58,132,.16)] backdrop-blur-xl sm:p-5"><div className="absolute -right-8 -top-10 h-40 w-40 rounded-full bg-clay-sun/30 blur-3xl" /><div className="relative"><div className="mb-4 flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-clay-purple">A connected class day</p><h2 className="mt-1 text-2xl">From roll call to recognition</h2></div><NovaAsset pose="welcome" priority className="-my-5 h-24 w-24 shrink-0 object-contain sm:h-28 sm:w-28" /></div><div className="grid gap-3 sm:grid-cols-2"><WorkflowCard icon="classes" label="1 · Teacher" title="Create a class" copy="Share its join code and approve students." /><WorkflowCard icon="attendance" label="2 · Class starts" title="Open QR attendance" copy="Students check in from their own device." tone="bg-[#eaf4ff]/90" /><WorkflowCard icon="assessment" label="3 · Learning" title="Assign & assess" copy="Activities, missions, submissions, and scores stay together." tone="bg-[#f1efff]/90" /><WorkflowCard icon="reward" label="4 · Progress" title="Reward effort" copy="XP, group points, badges, and requests show what’s growing." tone="bg-[#fff6df]/90" /></div></div></section>
      </section>

      <section id="tools" className="py-12 lg:py-16"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[.14em] text-clay-purple">The actual UniClass toolkit</p><h2 className="mt-3 text-4xl font-semibold sm:text-5xl">A practical home for the work around learning.</h2><p className="mt-4 text-lg leading-relaxed text-ink/75">UniClass supports the small, repeated actions that make a classroom run—without treating students as a spreadsheet.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2">{coreTools.map(([icon, title, copy]) => <article key={title} className="clay-card flex min-h-52 gap-4 p-5 sm:p-6"><div className="uc-icon-tile h-14 w-14 shrink-0 bg-gradient-to-br from-[#eeecff] to-[#dceeff]"><UIAsset name={icon} className="h-10 w-10" /></div><div className="min-w-0"><h3 className="text-2xl leading-tight">{title}</h3><p className="mt-2 leading-relaxed text-ink/75">{copy}</p></div></article>)}</div></section>

      <section id="for-whom" className="grid gap-4 py-12 lg:grid-cols-2 lg:py-16"><article className="relative overflow-hidden rounded-[28px] bg-[#273a82] p-7 text-white shadow-xl shadow-indigo-300/35 sm:p-9"><NovaAsset pose="thinking" className="absolute bottom-0 right-2 h-36 w-36 opacity-95 sm:h-44 sm:w-44" /><div className="relative max-w-sm"><p className="text-sm font-semibold uppercase tracking-[.14em] text-[#b8d8ff]">For teachers</p><h2 className="mt-3 text-4xl font-semibold leading-tight">A calmer command centre for the whole class.</h2><p className="mt-4 leading-relaxed text-white/85">Create classes, approve memberships, publish or review missions, record activities and scores, see attendance history, and handle reward or badge requests in one place.</p></div></article><article className="relative overflow-hidden rounded-[28px] bg-white/78 p-7 shadow-[0_16px_40px_rgba(47,58,132,.12)] ring-1 ring-white/85 backdrop-blur-xl sm:p-9"><NovaAsset pose="celebrate" className="absolute bottom-0 right-1 h-36 w-36 sm:h-44 sm:w-44" /><div className="relative max-w-sm"><p className="text-sm font-semibold uppercase tracking-[.14em] text-clay-purple">For students</p><h2 className="mt-3 text-4xl font-semibold leading-tight">A clearer way to participate and keep progressing.</h2><p className="mt-4 leading-relaxed text-ink/80">Join with a class code, scan attendance, complete missions, view scores, upload evidence for score edits, build personal XP, and contribute to group goals.</p></div></article></section>

      <section id="how-it-works" className="mb-12 grid gap-6 rounded-[30px] border border-white/85 bg-white/74 p-6 shadow-[0_16px_40px_rgba(47,58,132,.12)] backdrop-blur-xl sm:p-8 lg:grid-cols-[.8fr_1.2fr] lg:p-10"><div><p className="text-sm font-semibold uppercase tracking-[.14em] text-clay-purple">Why UniClass exists</p><h2 className="mt-3 text-4xl font-semibold leading-tight">Useful structure should still feel human.</h2><p className="mt-4 leading-relaxed text-ink/80">UniClass was built to connect administration, feedback, and encouragement in the same place—so effort is easier to notice and classroom progress has a shared record.</p><div className="mt-6 flex items-center gap-3 rounded-2xl bg-[#eef4ff] p-3"><div className="uc-icon-tile h-11 w-11 bg-white"><UsersRound className="h-5 w-5 text-clay-purple" /></div><p className="text-sm font-medium text-ink/80">Supports group-based classes and individual student access.</p></div></div><ol className="grid gap-3">{[["01", "Create the class", "Add its details and share the class code."], ["02", "Run a visible routine", "Use QR check-ins, activities, missions, scores, and announcements."], ["03", "Recognise real progress", "Use XP, points, rewards, badges, and the leaderboard to celebrate effort."]].map(([number, title, copy]) => <li key={number} className="flex items-start gap-4 rounded-2xl bg-white/85 p-4 shadow-sm ring-1 ring-white"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edeaff] text-sm font-semibold text-clay-purple">{number}</span><div><h3 className="text-xl leading-tight">{title}</h3><p className="mt-1 text-sm leading-relaxed text-ink/75">{copy}</p></div></li>)}</ol></section>

      <section className="mb-12 rounded-[30px] bg-[#273a82] p-7 text-center text-white shadow-xl shadow-indigo-300/35 sm:p-10"><p className="text-sm font-semibold uppercase tracking-[.14em] text-[#b8d8ff]">Ready when your class is</p><h2 className="mx-auto mt-3 max-w-2xl text-4xl font-semibold leading-tight sm:text-5xl">Bring your classroom’s work and wins into one place.</h2><p className="mx-auto mt-4 max-w-xl text-white/80">Teachers create a class. Students join with its code. Everyone sees the routine move forward.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Button onClick={() => navigate(ROUTES.REGISTER)} className="bg-clay-sun text-ink">Create an account <ArrowRight className="h-4 w-4" /></Button><Button onClick={() => navigate(ROUTES.LOGIN)} className="bg-white text-ink">Log in</Button></div></section>
    </main>
    <footer className="relative z-10 border-t border-white/70 bg-white/60 px-4 py-6 text-center text-sm text-ink/70 backdrop-blur">UniClass · Classroom routines, progress, and recognition in one shared space.</footer>
  </div>;
}
